name: E2E sTPS Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      # toolchain
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-12-01
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
          override: true
          default: true
      # zombienet
      - name: Run zombienet
        run: |
          # Prevent the zombienet.sh script from building the collator since it is not needed.
          mkdir -p target/release
          echo "not needed" > target/release/parachain-collator
          
          ./zombienet.sh test tests/examples/solo.feature
