name: E2E sTPS Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # toolchain
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-12-01
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
          override: true
          default: true
      # zombienet
      - name: Run zombienet
        run: |
          ./polkadot-stps.sh test tests/stps/relay-single-node.zndsl
